dingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('', include("greetings.urls")),
    path('sessions/', include("sessions.urls")),
]

maths/urls.py
from django.urls import path
from .views import math, add, sub, mul, div, maths_list, math_details, results_list

app_name="maths"
urlpatterns = [
   path('', math),
   path('add/<a>/<b>', add),
   path('sub/<a>/<b>', sub),
   path('mul/<a>/<b>', mul),
   path('div/<a>/<int:b>', div),
   path('histories/', maths_list, name="list"),
   path('histories/<int:id>', math_details, name="details"),
   path('results/', results_list, name="results"),
]

maths/models.py
from django.db import models

# Create your models here.

OPERATION_CHOICES = (
   ("add", "add"),
   ("sub", "sub"),
   ("mul", "mul"),
   ("div", "div"),
)

class Math(models.Model):
    operation = models.CharField(max_length=5, choices=OPERATION_CHOICES)
    a = models.IntegerField()
    b = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    result = models.ForeignKey(
      'maths.Result',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"id:{self.id}, a={self.a}, b={self.b}, op={self.operation}"
    
    class Meta:
       ordering = ["-id"]


class Result(models.Model):
    value = models.FloatField(blank=True, null=True, unique=True)
    error = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        unique=True
    )

    def __str__(self):
        return f"value:{self.value} | error:{self.error}"


    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_value_error_together",
                check=(
                    models.Q(
                        value__isnull=False,
                        error__isnull=True,
                    )
                    | models.Q(
                        value__isnull=True,
                        error__isnull=False,
                    )
                )
            )
        ]

maths/forms.py
from django import forms
from maths.models import Result

class ResultForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        value = cleaned_data.get('value')
        error = cleaned_data.get('error')

        if value and error:
            raise forms.ValidationError("Podaj tylko jedną z wartości")
        elif not (value or error):
            raise forms.ValidationError("Nie podano żadnej wartości!")   
    
    class Meta:
        model = Result
        fields = ["value", "error"]

maths/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.contrib import messages
from maths.models import Math, Result
from maths.forms import ResultForm
from django.core.paginator import Paginator


# Create your views here.

def math(request):
   return render(
    	    request=request,
    	    template_name="maths/main.html"
	)

def add(request, a, b):
    a, b = int(a), int(b)
    wynik = a+b
    c = {"a":a, "b":b, "operacja": "+" ,"wynik":wynik, "title": "dodawanie"}

    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='add', a=a, b=b, result=result)

    return render(
        request=request,
        template_name="operation.html",
        context=c
    )

def sub(request, a, b):
    a, b = int(a), int(b)
    wynik = a - b
    c = {"a":a, "b":b, "operacja": "-" ,"wynik":wynik, "title": "odejmowanie"}

    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='sub', a=a, b=b, result=result)

    return render(
        request=request,
        template_name="operation.html",
        context=c
    )

def mul(request, a, b):
    a, b = int(a), int(b)
    wynik = a*b
    c = {"a":a, "b":b, "operacja": "*" ,"wynik":wynik, "title": "mnozenie"}

    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='mul', a=a, b=b, result=result)

    return render(
            request=request,
            template_name="operation.html",
            context=c
    )

def div(request, a, b):
    if int(b) == 0:
        wynik = "Error"
        messages.add_message(request, messages.ERROR, "Dzielenie przez zero!")
    else:
        wynik = int(a) / int(b)
        c = {"a": a, "b": b, "operacja": "/", "wynik": wynik, "title": "dzielenie"}

    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='div', a=a, b=b, result=result)

    return render(
        request=request,
        template_name="operation.html",
        context=c
    )

def maths_list(request):
   maths = Math.objects.all()
   paginator = Paginator(maths, 5)
   page_number = request.GET.get('page')
   maths = paginator.get_page(page_number)
   return render(
       request=request,
       template_name="maths/list.html",
       context={"maths": maths}
   )

def math_details(request, id):
    math = Math.objects.get(id=id)
    return render(
        request=request,
        template_name='maths/details.html',
        context={"math": math}
    )

def results_list(request):
   if request.method == "POST":
       form = ResultForm(data=request.POST)

       if form.is_valid():
           if form.cleaned_data['error'] == '':
               form.cleaned_data['error'] = None
           form.save()
           messages.add_message(
               request,
               messages.SUCCESS,
               "Utworzono nowy Result!!"
           )
       else:
           messages.add_message(
               request,
               messages.ERROR,
               form.errors['__all__']
           )

   form = ResultForm()
   results = Result.objects.all()
   return render(
       request=request,
       template_name="maths/results.html",
       context={
           "results": results,
           "form": form
       }
   )

maths/templates/maths/details.html
{% extends "main.html" %}

{% block title %}Math details{% endblock %}

{% block content %}
   <table>
       <tr>
           <th>Operation</th>
           <td>{{ math.operation }}</td>
       </tr>
       <tr>
           <th>a</th>
           <td>{{ math.a }}</td>
       </tr>
       <tr>
           <th>b</th>
           <td>{{ math.b }}</td>
       </tr>
       <tr>
           <th>Created:</th>
           <td>{{ math.created }}</td>
       </tr>
       <tr>
           <th>Result</th>
           <td>{{ math.result }}</td>
       </tr>
   </table>
   <a href="{% url "maths:list" %}">back</a>
{% endblock %}

maths/templates/maths/list.html
{% extends 'main.html' %}

{% block title %}
  Maths list
{% endblock %}

{% block content %}
  <h3>Wyniki</h3>
  <ul class="list-group">
    {% for m in maths %}
      <li class="list-group-item">
        <a href="{% url 'maths:details' m.id %}">{{ m }}</a>
      </li>
    {% endfor %}
  </ul>
  <div class="pagination">
    <span class="step-links">
      {% if maths.has_previous %}
        <a href="?page=1">« first</a>
        <a href="?page={{ maths.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">Page {{ maths.number }} of {{ maths.paginator.num_pages }}.</span>

      {% if maths.has_next %}
        <a href="?page={{ maths.next_page_number }}">next</a>
        <a href="?page={{ maths.paginator.num_pages }}">last »</a>
      {% endif %}
    </span>
  </div>
{% endblock %}

maths/templates/maths/results.html
{% extends 'main.html' %}

{% block title %}
  Results list
{% endblock %}

{% block content %}
  <h3>Results</h3>
  <ul class="list-group">
    {% for r in results %}
      <li class="list-group-item">{{ r }}</li>
    {% endfor %}
  </ul>

  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="go" />
  </form>
{% endblock %}