dingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('', include("greetings.urls")),
    path('sessions/', include("sessions.urls")),
]

greetings/urls.py
from django.urls import path
from .views import greetings, about, contact

app_name='greetings'
urlpatterns = [
   path('', greetings, name='welcome'),
   path('about/', about, name='about'),
   path('contact/', contact, name='contact')
]

maths/urls.py
from django.urls import path
from .views import math, add, sub, mul, div, maths_list, math_details, results_list

app_name="maths"
urlpatterns = [
   path('', math),
   path('add/<a>/<b>', add),
   path('sub/<a>/<b>', sub),
   path('mul/<a>/<b>', mul),
   path('div/<a>/<int:b>', div),
   path('histories/', maths_list, name="list"),
   path('histories/<int:id>', math_details, name="details"),
   path('results/', results_list, name="results"),
]

posts/urls.py
from django.urls import path
from .views import posts_list, post_details, authors_list, author_details

app_name="posts"
urlpatterns = [
   path('post/<int:id>', post_details, name="details"),
   path('list/', posts_list, name="list"),
   path('authors/list/', authors_list, name="authors_list"),
   path('author/<int:id>', author_details, name="authors_details")
]

templates/main.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>
      {% block title %}
        Title
      {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'maths/css/style.css' %}" />

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <div class="container">
      <div id="content">
        <div id="header">
          <nav class="navbar navbar-expand-md navbar-dark bg-primary" id="navigation">
            <div class="container-fluid">
              <a class="navbar-brand abs" href="/">App</a>
              <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar"><span class="navbar-toggler-icon"></span></button>
              <div class="navbar-collapse collapse" id="collapseNavbar">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href={% url "greetings:welcome" %}>Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "maths:list" %}>Maths</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "posts:list" %}>Posts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "greetings:about" %}>About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "greetings:contact" %}>Kontakt</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>

        {% bootstrap_messages %}
        <div class="container">
          <div id="inner-content" style="padding: 20px;">
            <div class="row">
              {% block content %}
                To jest blok kodu. W innych szablonach możemy go nadpisać
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>
        $(function () {
          if (location.pathname.split('/')[1] == '') {
            $('nav a[href^="' + window.location.href + '"]').addClass('active')
          } else {
            $('nav a[href^="/' + location.pathname.split('/')[1] + '"]').addClass('active')
          }
          $(this).removeClass('active')
        })
      </script>
      <footer style="text-align: center; padding: 5px; color: white;" class="bg-primary footer">App @copyright 2024 Michał Kaczmarek </footer>
    </div>
    
  </body>
</html>