dingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('', include("greetings.urls")),
    path('sessions/', include("sessions.urls")),
]

posts/urls.py
from django.urls import path
from .views import posts_list, post_details, authors_list, author_details

app_name="posts"
urlpatterns = [
   path('post/<int:id>', post_details, name="details"),
   path('list/', posts_list, name="list"),
   path('authors/list/', authors_list, name="authors_list"),
   path('author/<int:id>', author_details, name="authors_details")
]

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )
    author = models.ForeignKey(
        'posts.Author',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"title:{self.title}, autor:{self.author}"


class Author(models.Model):
    nick = models.CharField(max_length=20)
    email = models.EmailField()
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"nick:{self.nick} | email:{self.email}"

posts/forms.py
from django import forms
from posts.models import Post, Author

class PostForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        author = cleaned_data.get('author')

        if not (title and content and author):
            raise forms.ValidationError("Nie podano żadnej wartości!")
        
    class Meta:
        model = Post
        fields = "__all__"

        
class AuthorForm(forms.ModelForm):
    field_order = ['email', 'nick', 'bio']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        bio = cleaned_data.get('bio')
        nick = cleaned_data.get('nick')

        if not (email and nick):
            raise forms.ValidationError("Nie podano wymaganych pól")
        
    class Meta:
        model = Author
        fields = "__all__"

posts/views.py
from django.shortcuts import render
from posts.models import Post, Author
from posts.forms import PostForm, AuthorForm
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.


def posts_list(request):
    if request.method == "POST":
        form = PostForm(data=request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowy post!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = PostForm()
    posts = Post.objects.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    return render(
        request=request,
        template_name="posts/list.html",
        context={
            "posts": posts,
            "form": form
        }
    )


def post_details(request, id):
    post = Post.objects.get(id=id)
    return render(
        request=request,
        template_name='posts/details.html',
        context={"post": post}
    )


def authors_list(request):
    if request.method == "POST":
        form = AuthorForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowego autora!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form_author = AuthorForm()
    authors = Author.objects.all()
    return render(
        request=request,
        template_name="authors/list.html",
        context={
            "authors": authors,
            "form_author": form_author
        }
    )


def author_details(request, id):
    author = Author.objects.get(id=id)
    return render(
        request=request,
        template_name='authors/details.html',
        context={"author": author}
    )

posts/templates/posts/details.html
{% extends "main.html" %}

{% block title %}Post details{% endblock %}

{% block content %}
   <table>
       <tr>
           <th>Title</th>
           <td>{{ post.title }}</td>
       </tr>
       <tr>
           <th>Content</th>
           <td>{{ post.content }}</td>
       </tr>
       <tr>
           <th>Author</th>
           <td>{{ post.author }}</td>
       </tr>
   </table>
   <a href="{% url "posts:list" %}">back</a>
{% endblock %}

posts/templates/posts/list.html
{% extends 'main.html' %}

{% load django_bootstrap5 %}

{% block title %}
  Posts list
{% endblock %}

{% block content %}
<div class="col">
  <h3>Lista postów</h3>
  <ul class="list-group">
    {% for p in posts %}
      <li class="list-group-item">
        <a href="{% url 'posts:details' p.id %}">{{ p }}</a>
      </li>
    {% endfor %}
  </ul>
  <div class="pagination">
    <span class="step-links">
      {% if posts.has_previous %}
        <a href="?page=1">« first</a>
        <a href="?page={{ posts.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">Page {{ posts.number }} of {{ posts.paginator.num_pages }}.</span>

      {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">next</a>
        <a href="?page={{ posts.paginator.num_pages }}">last »</a>
      {% endif %}
    </span>
  </div>
</div>
<div class="col">
  <h4>Dodaj post</h4>

  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <input type="submit" value="go" class="btn btn-primary"/>
    
  </form>
</div>
{% endblock %}